"""adding enw address column

Revision ID: a45788bf0287
Revises: f75785dcff28
Create Date: 2022-01-24 00:19:09.997606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45788bf0287'
down_revision = 'f75785dcff28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auths', sa.Column('address', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auths', 'address')
    # ### end Alembic commands ###
