"""address column

Revision ID: c54458b80fc3
Revises: e93b9b8ac3cc
Create Date: 2022-01-23 17:03:05.841440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54458b80fc3'
down_revision = 'e93b9b8ac3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auths', sa.Column('address', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auths', 'address')
    # ### end Alembic commands ###
