"""creat new address col

Revision ID: dc6b5d7517a5
Revises: 4735781d7be2
Create Date: 2022-01-24 02:05:13.443535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc6b5d7517a5'
down_revision = '4735781d7be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auths', sa.Column('address', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auths', 'address')
    # ### end Alembic commands ###
