"""add new column title

Revision ID: dd6349ecf334
Revises: e4c64a793584
Create Date: 2022-01-11 05:15:41.622111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6349ecf334'
down_revision = 'e4c64a793584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auths', sa.Column('title', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auths', 'title')
    # ### end Alembic commands ###
