"""add column status

Revision ID: e93b9b8ac3cc
Revises: dd6349ecf334
Create Date: 2022-01-12 03:57:44.835981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93b9b8ac3cc'
down_revision = 'dd6349ecf334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auths', sa.Column('status', sa.String(length=32), default='active', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auths', 'status')
    # ### end Alembic commands ###
