"""remove address

Revision ID: f75785dcff28
Revises: c54458b80fc3
Create Date: 2022-01-23 23:31:15.764177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f75785dcff28'
down_revision = 'c54458b80fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auths', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auths', sa.Column('address', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
